theme: minima
minima:
  skin: auto
  nav_pages:
    - index.md
    - notes.md
    - resources.md
    - ph-ormula.md
title: PHCubers
description: Website for PHCubers
url: "https://phcubers.github.io"
exclude:
  - README.md
  - _site/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .bundle/
  - Gemfile.lock
kramdown:
  math_engine: mathjax
